# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from anniegodfather.proto import anniedad_pb2 as anniegodfather_dot_proto_dot_anniedad__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in anniegodfather/proto/anniedad_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MediaStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PostURL = channel.unary_unary(
                '/main.Media/PostURL',
                request_serializer=anniegodfather_dot_proto_dot_anniedad__pb2.PostMediaRequest.SerializeToString,
                response_deserializer=anniegodfather_dot_proto_dot_anniedad__pb2.PostMediaResponse.FromString,
                _registered_method=True)
        self.GetURL = channel.unary_unary(
                '/main.Media/GetURL',
                request_serializer=anniegodfather_dot_proto_dot_anniedad__pb2.GetMediaRequest.SerializeToString,
                response_deserializer=anniegodfather_dot_proto_dot_anniedad__pb2.GetMediaResponse.FromString,
                _registered_method=True)
        self.GetListURL = channel.unary_unary(
                '/main.Media/GetListURL',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=anniegodfather_dot_proto_dot_anniedad__pb2.GetMediaResponse.FromString,
                _registered_method=True)


class MediaServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PostURL(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetURL(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetListURL(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MediaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PostURL': grpc.unary_unary_rpc_method_handler(
                    servicer.PostURL,
                    request_deserializer=anniegodfather_dot_proto_dot_anniedad__pb2.PostMediaRequest.FromString,
                    response_serializer=anniegodfather_dot_proto_dot_anniedad__pb2.PostMediaResponse.SerializeToString,
            ),
            'GetURL': grpc.unary_unary_rpc_method_handler(
                    servicer.GetURL,
                    request_deserializer=anniegodfather_dot_proto_dot_anniedad__pb2.GetMediaRequest.FromString,
                    response_serializer=anniegodfather_dot_proto_dot_anniedad__pb2.GetMediaResponse.SerializeToString,
            ),
            'GetListURL': grpc.unary_unary_rpc_method_handler(
                    servicer.GetListURL,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=anniegodfather_dot_proto_dot_anniedad__pb2.GetMediaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'main.Media', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('main.Media', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Media(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PostURL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/main.Media/PostURL',
            anniegodfather_dot_proto_dot_anniedad__pb2.PostMediaRequest.SerializeToString,
            anniegodfather_dot_proto_dot_anniedad__pb2.PostMediaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetURL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/main.Media/GetURL',
            anniegodfather_dot_proto_dot_anniedad__pb2.GetMediaRequest.SerializeToString,
            anniegodfather_dot_proto_dot_anniedad__pb2.GetMediaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetListURL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/main.Media/GetListURL',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            anniegodfather_dot_proto_dot_anniedad__pb2.GetMediaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
