# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: anniegodfather/proto/anniedad.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'anniegodfather/proto/anniedad.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#anniegodfather/proto/anniedad.proto\x12\x04main\x1a\x1bgoogle/protobuf/empty.proto\"$\n\x10PostMediaRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\" \n\x11PostMediaResponse\x12\x0b\n\x03url\x18\x01 \x01(\t\"#\n\x0fGetMediaRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"\x1f\n\x10GetMediaResponse\x12\x0b\n\x03url\x18\x01 \x01(\t\"!\n\x12GetListURLResponse\x12\x0b\n\x03url\x18\x01 \x03(\t2\xba\x01\n\x05Media\x12:\n\x07PostURL\x12\x16.main.PostMediaRequest\x1a\x17.main.PostMediaResponse\x12\x37\n\x06GetURL\x12\x15.main.GetMediaRequest\x1a\x16.main.GetMediaResponse\x12<\n\nGetListURL\x12\x16.google.protobuf.Empty\x1a\x16.main.GetMediaResponseB;Z9github.com/sebasttiano13/AnnieDad/internal/proto/anniedadb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'anniegodfather.proto.anniedad_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z9github.com/sebasttiano13/AnnieDad/internal/proto/anniedad'
  _globals['_POSTMEDIAREQUEST']._serialized_start=74
  _globals['_POSTMEDIAREQUEST']._serialized_end=110
  _globals['_POSTMEDIARESPONSE']._serialized_start=112
  _globals['_POSTMEDIARESPONSE']._serialized_end=144
  _globals['_GETMEDIAREQUEST']._serialized_start=146
  _globals['_GETMEDIAREQUEST']._serialized_end=181
  _globals['_GETMEDIARESPONSE']._serialized_start=183
  _globals['_GETMEDIARESPONSE']._serialized_end=214
  _globals['_GETLISTURLRESPONSE']._serialized_start=216
  _globals['_GETLISTURLRESPONSE']._serialized_end=249
  _globals['_MEDIA']._serialized_start=252
  _globals['_MEDIA']._serialized_end=438
# @@protoc_insertion_point(module_scope)
