# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from anniegodfather.proto import anniedad_pb2 as anniegodfather_dot_proto_dot_anniedad__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in anniegodfather/proto/anniedad_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MediaStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PostURLs = channel.unary_unary(
                '/main.Media/PostURLs',
                request_serializer=anniegodfather_dot_proto_dot_anniedad__pb2.PostMediaRequest.SerializeToString,
                response_deserializer=anniegodfather_dot_proto_dot_anniedad__pb2.PostMediaResponse.FromString,
                _registered_method=True)
        self.GetURLs = channel.unary_unary(
                '/main.Media/GetURLs',
                request_serializer=anniegodfather_dot_proto_dot_anniedad__pb2.GetMediaRequest.SerializeToString,
                response_deserializer=anniegodfather_dot_proto_dot_anniedad__pb2.GetMediaResponse.FromString,
                _registered_method=True)


class MediaServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PostURLs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetURLs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MediaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PostURLs': grpc.unary_unary_rpc_method_handler(
                    servicer.PostURLs,
                    request_deserializer=anniegodfather_dot_proto_dot_anniedad__pb2.PostMediaRequest.FromString,
                    response_serializer=anniegodfather_dot_proto_dot_anniedad__pb2.PostMediaResponse.SerializeToString,
            ),
            'GetURLs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetURLs,
                    request_deserializer=anniegodfather_dot_proto_dot_anniedad__pb2.GetMediaRequest.FromString,
                    response_serializer=anniegodfather_dot_proto_dot_anniedad__pb2.GetMediaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'main.Media', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('main.Media', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Media(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PostURLs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/main.Media/PostURLs',
            anniegodfather_dot_proto_dot_anniedad__pb2.PostMediaRequest.SerializeToString,
            anniegodfather_dot_proto_dot_anniedad__pb2.PostMediaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetURLs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/main.Media/GetURLs',
            anniegodfather_dot_proto_dot_anniedad__pb2.GetMediaRequest.SerializeToString,
            anniegodfather_dot_proto_dot_anniedad__pb2.GetMediaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
