# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: anniegodfather/proto/anniegodfather.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'anniegodfather/proto/anniegodfather.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)anniegodfather/proto/anniegodfather.proto\x12\x04main\x1a\x1bgoogle/protobuf/empty.proto\"1\n\x0fRegisterRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\".\n\x0cLoginRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1e\n\rLoginResponse\x12\r\n\x05token\x18\x01 \x01(\t\"\x12\n\x10PostMediaRequest\" \n\x11PostMediaResponse\x12\x0b\n\x03url\x18\x01 \x01(\t2s\n\x04\x41uth\x12\x39\n\x08Register\x12\x15.main.RegisterRequest\x1a\x16.google.protobuf.Empty\x12\x30\n\x05Login\x12\x12.main.LoginRequest\x1a\x13.main.LoginResponse2J\n\x0cPresignedURL\x12:\n\x07PostURL\x12\x16.main.PostMediaRequest\x1a\x17.main.PostMediaResponseB2Z0github.com/sebasttiano13/AnnieDad/internal/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'anniegodfather.proto.anniegodfather_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z0github.com/sebasttiano13/AnnieDad/internal/proto'
  _globals['_REGISTERREQUEST']._serialized_start=80
  _globals['_REGISTERREQUEST']._serialized_end=129
  _globals['_LOGINREQUEST']._serialized_start=131
  _globals['_LOGINREQUEST']._serialized_end=177
  _globals['_LOGINRESPONSE']._serialized_start=179
  _globals['_LOGINRESPONSE']._serialized_end=209
  _globals['_POSTMEDIAREQUEST']._serialized_start=211
  _globals['_POSTMEDIAREQUEST']._serialized_end=229
  _globals['_POSTMEDIARESPONSE']._serialized_start=231
  _globals['_POSTMEDIARESPONSE']._serialized_end=263
  _globals['_AUTH']._serialized_start=265
  _globals['_AUTH']._serialized_end=380
  _globals['_PRESIGNEDURL']._serialized_start=382
  _globals['_PRESIGNEDURL']._serialized_end=456
# @@protoc_insertion_point(module_scope)
