# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from anniegodfather.proto import auth_pb2 as anniegodfather_dot_proto_dot_auth__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in anniegodfather/proto/auth_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterTelegram = channel.unary_unary(
                '/main.AuthService/RegisterTelegram',
                request_serializer=anniegodfather_dot_proto_dot_auth__pb2.TelegramRegisterRequest.SerializeToString,
                response_deserializer=anniegodfather_dot_proto_dot_auth__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.LoginTelegram = channel.unary_unary(
                '/main.AuthService/LoginTelegram',
                request_serializer=anniegodfather_dot_proto_dot_auth__pb2.TelegramLoginRequest.SerializeToString,
                response_deserializer=anniegodfather_dot_proto_dot_auth__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.RefreshToken = channel.unary_unary(
                '/main.AuthService/RefreshToken',
                request_serializer=anniegodfather_dot_proto_dot_auth__pb2.RefreshRequest.SerializeToString,
                response_deserializer=anniegodfather_dot_proto_dot_auth__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.LinkWeb = channel.unary_unary(
                '/main.AuthService/LinkWeb',
                request_serializer=anniegodfather_dot_proto_dot_auth__pb2.LinkWebRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class AuthServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterTelegram(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoginTelegram(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LinkWeb(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterTelegram': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterTelegram,
                    request_deserializer=anniegodfather_dot_proto_dot_auth__pb2.TelegramRegisterRequest.FromString,
                    response_serializer=anniegodfather_dot_proto_dot_auth__pb2.AuthResponse.SerializeToString,
            ),
            'LoginTelegram': grpc.unary_unary_rpc_method_handler(
                    servicer.LoginTelegram,
                    request_deserializer=anniegodfather_dot_proto_dot_auth__pb2.TelegramLoginRequest.FromString,
                    response_serializer=anniegodfather_dot_proto_dot_auth__pb2.AuthResponse.SerializeToString,
            ),
            'RefreshToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshToken,
                    request_deserializer=anniegodfather_dot_proto_dot_auth__pb2.RefreshRequest.FromString,
                    response_serializer=anniegodfather_dot_proto_dot_auth__pb2.AuthResponse.SerializeToString,
            ),
            'LinkWeb': grpc.unary_unary_rpc_method_handler(
                    servicer.LinkWeb,
                    request_deserializer=anniegodfather_dot_proto_dot_auth__pb2.LinkWebRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'main.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('main.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterTelegram(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/main.AuthService/RegisterTelegram',
            anniegodfather_dot_proto_dot_auth__pb2.TelegramRegisterRequest.SerializeToString,
            anniegodfather_dot_proto_dot_auth__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoginTelegram(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/main.AuthService/LoginTelegram',
            anniegodfather_dot_proto_dot_auth__pb2.TelegramLoginRequest.SerializeToString,
            anniegodfather_dot_proto_dot_auth__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/main.AuthService/RefreshToken',
            anniegodfather_dot_proto_dot_auth__pb2.RefreshRequest.SerializeToString,
            anniegodfather_dot_proto_dot_auth__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LinkWeb(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/main.AuthService/LinkWeb',
            anniegodfather_dot_proto_dot_auth__pb2.LinkWebRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
